/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.xiaomi.xsupervisor.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * status of operation.
 */
public enum OperationStatus implements TEnum {
  Ok(0),
  Fail(1);

  private final int value;

  private OperationStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OperationStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return Ok;
      case 1:
        return Fail;
      default:
        return null;
    }
  }
}
